name: core
description: A new Flutter package.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.12
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  retrofit: ^2.0.0
  logger: any
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0
  shimmer: ^2.0.0
  get_it: ^7.1.3
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  cached_network_image: ^3.1.0
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.0.8
  flutter_svg: ^0.22.0
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_easyloading: ^3.0.0
  jwt_decoder: ^2.0.1
  permission_handler: ^8.1.4+2
  file_picker: ^3.0.2+2
  mime_type: ^1.0.0
  cross_file: ^0.3.1+4
  injectable: ^1.4.1
  html_editor_enhanced: ^2.2.0
  # flutter_html: ^2.1.0
  flutter_html: ^2.2.1
  signalr_core: ^1.1.1
  # signalr_netcore: ^1.3.0
  qr_code_scanner: ^0.5.2
  flutter_inappwebview: ^5.3.2
  flutter_datetime_picker: ^1.5.1
  dotted_border: ^2.0.0+1
  alice:
    path: ../alice/
  share_plus: ^3.0.4
  just_audio: ^0.9.15
  matomo: ^1.1.0
  flutter_local_notifications: ^8.2.0
  flutter_screenutil: ^5.0.0+2
  carousel_slider: ^4.0.0-nullsafety.0
  dartz: ^0.10.0
  flutter_math:
    path: ../flutter-math/
  connectivity: ^3.0.6
  flutter_spinkit: ^5.1.0
  local_auth: ^1.1.8
  app_settings: ^4.1.1
  lottie: ^1.1.0
  animations: ^2.0.2
  path_provider: ^2.0.8
  expandable_text: ^2.2.0
  flutter_staggered_grid_view: ^0.6.0
  flutter_rating_bar: ^4.0.0
  # in_app_review: ^2.0.4
  flutter_widget_from_html_core: ^0.8.5+1
  in_app_purchase: ^1.0.9
  photo_view: ^0.14.0
  image_picker: ^0.8.0
  qr_flutter: ^4.0.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.4.0
  #  passcode_screen: ^2.0.1
  in_app_update: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #    retrofit_generator: any
  build_runner: ^2.0.4
  freezed: ^0.14.2
  api:
    path: ../api/
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart.git
      ref: 9f90296751984b359937c38563da5b19db5550f5
      path: generator
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/image/
    - lib/assets/images/image_guide/
    - lib/assets/images/image_learn/
    - lib/assets/images/image_event/
    - lib/assets/images/image_chat/

  fonts:
    # - family: AppIcons
    #   fonts:
    #     - asset: lib/res/fonts/AppIcons.ttf
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700
