name: vitan_edu
description: A new Flutter application.

publish_to: "none"
version: 1.0.0+28

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  api:
    path: ../api/
  core:
    path: ../core/
  exam:
    path: ../exam/
  contest:
    path: ../contest/
  guide:
    path: ../guide/ 
  learn:
    path: ../learn/
  common:
    path: ../common/
  carousel_slider: ^4.0.0-nullsafety.0
  url_launcher: ^6.0.12
  flutter_bloc: ^7.0.0
  dio: ^4.0.0
  retrofit: ^2.0.0
  logger: any
  json_annotation: ^4.0.1
  json_serializable: ^4.0.1
  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  injectable: ^1.4.1
  shared_preferences: ^2.0.6
  dotted_border: ^2.0.0
  equatable: ^2.0.3
  flutter_native_splash: ^1.2.0
  path_provider: ^2.0.2
  shimmer: ^2.0.0
  flutter_html: ^2.1.0
  expandable: ^5.0.1
  modal_bottom_sheet: ^2.0.0
  pull_to_refresh: ^2.0.0
  tuple: ^2.0.0
  flutter_inappwebview: ^5.3.2
  intl: ^0.17.0
  lottie: ^1.1.0
  flutter_screenutil: 5.3.1
  screenshot: ^1.2.3
  firebase_messaging: ^10.0.0
  firebase_core: ^1.7.0
  flutter_local_notifications: ^8.2.0
  dotted_line: ^3.0.1
  # dependency_overrides:
  #   flutter_colorpicker: ^0.4.0
  share_plus: ^3.0.4
  uuid: ^3.0.5
  expandable_text: ^2.2.0
  flutter_launcher_icons: ^0.9.2
  uni_links: ^0.5.1
  #social login
  flutter_facebook_auth: ^3.5.6
  google_sign_in: ^5.2.1
  sign_in_with_apple: ^3.3.0
  scroll_to_index: any
  flutter_radar_chart: ^0.2.0
  passcode_screen: ^2.0.1
  extended_nested_scroll_view: ^5.0.0
  scroll_bottom_navigation_bar: ^4.0.0
  auto_size_text: ^3.0.0
  package_info_plus: ^1.4.0
  version: ^2.0.0
  permission_handler: ^8.1.4+2
  sliver_tools: ^0.2.5
  simple_gradient_text: ^1.2.2
  flutter_widget_from_html_core: ^0.8.5+1
  #awesome notifications
  awesome_notifications: any
#  cupertino_will_pop_scope: ^1.2.0
  photo_view: ^0.14.0
  in_app_update: ^3.0.0

  #dynamic link
  firebase_dynamic_links:

dependency_overrides:
  flutter_colorpicker: ^0.6.0
  percent_indicator: 4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.2
  build_runner: ^2.0.4
  injectable_generator:
  retrofit_generator: ^2.0.0+2
  freezed: ^0.14.2
  # device_preview: ^0.7.0

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "lib/core/assets/icon/710x599.png"
  image_path_ios: "lib/core/assets/icon/1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_foreground: "lib/core/assets/icon/432x432.png" # only available for Android 8.0 devices and above

#  retrofit_generator:
#    git:
#      url: https://github.com/Chimerapps/retrofit.dart.git
#      ref: 9f90296751984b359937c38563da5b19db5550f5
#      path: generator
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/core/language/vi.json
    - lib/core/language/en.json
    - assets/webpages/
    - assets/

  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf
        - asset: fonts/Sarabun-Italic.ttf
          style: italic
        - asset: fonts/Sarabun-Medium.ttf
          weight: 500
        - asset: fonts/Sarabun-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Sarabun-SemiBold.ttf
          weight: 600
        - asset: fonts/Sarabun-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Sarabun-Bold.ttf
          weight: 700
        - asset: fonts/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Sarabun-ExtraBold.ttf
          weight: 800
        - asset: fonts/Sarabun-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: SVN-Gilroy
      fonts:
        - asset: fonts/SVN-Gilroy-Regular.otf
        - asset: fonts/SVN-Gilroy-Italic.otf
          style: italic
        - asset: fonts/SVN-Gilroy Medium.otf
          weight: 500
        - asset: fonts/SVN-Gilroy Medium Italic.otf
          weight: 500
          style: italic
        - asset: fonts/SVN-Gilroy-SemiBold.otf
          weight: 600
        - asset: fonts/SVN-Gilroy-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/SVN-Gilroy-Bold.otf
          weight: 700
        - asset: fonts/SVN-Gilroy-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/SVN-Gilroy-XBold.otf
          weight: 800
        - asset: fonts/SVN-Gilroy-XBoldItalic.otf
          weight: 800
          style: italic

flutter_native_splash:
  #  color: "#42a5f5"
  background_image: "lib/core/assets/splash_no_text.png"
